--- 
- hosts: 10.0.3.231
  become: yes
  task: 
  - name: i want to excute linux command
    command: hostname -f
    register: myvariable
  
  - name: i want to display first task result
    debug:
      msg: "{{myvariable}}"