--- 
- hosts: 10.0.3.231
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
       name: apache2
       state: present

  - name: copy index.html file into nodes side
    copy:
       src: index.html
       dest: /var/www/html/index.html

  - name: copy myindex.j2 file into nodes side
    template:
       src: myindex.j2
       dest: /var/www/html/index.html 