---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu
    apt:
       name: "{{myjavapackonubuntu}}"
       state: present
    when: ansible_os_family =="Debian"

  - name: install webserver on RedHat nodes
    yum:
       name: "{{myjavapackonredhat}}"
       state: present
    when: ansible_os_family =="RedHat"