--- 
- hosts: 10.0.3.231
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
       name: apache2
       state: present

  - name: copy index.html file into nodes  side
    ansible.builtin.copy:
            src: myindex.html
            dest: /var/www/html/index.html

  - name: copy index.j2 file into nodes side
    ansible.builtin.template:
            src: index.j2
            dest: /var/www/html/index.html   
    notify: restart webserver         

  - name: i want to download remote(internet) files
    ansible.builtin.get_url:
           url: https://get.jenkins.io/war-stable/2.414.2/jenkins.war
           dest: /home/ubuntu/jenkins.war 
           force_basic_auth: yes


  handlers:
  - name: restart webserver
    service:
       name: apache2
       state: restarted
  #  remote file added  